Make tkinter window appear, make other errors disappear
1. Why was tkinter window not appearing?
  - The __init__ method was never called because `MyGUI` was never "instantiated".
  - `my_gui` was a reference to the class, not a reference to an object of the class.
  - The end result was that you defined the class, but never used the class.
  - I fixed this by adding parenthesis, making it `my_gui = MyGUI()`, which made my_gui reference an instantiated object of the class, in turn calling the __init__ method, and running all the tkinter stuff.
2. What happened after I added the parentheses?
  - I got an error `AttributeError: 'MyGUI' object has no attribute 'calculate'`
  - I fixed this error by defining a method called "calculate"
3.  What happened next?
  - I got another error.  `TypeError: calculate() takes 0 positional arguments but 1 was given` on the calculate function
  - I fixed this error by defining an argument to the calculate function I added.